name: ScythePlugin
version: 1.0.0-SNAPSHOT
main: com.dreamfirestudios.scytheplugin.ScythePlugin
depend: [ProtocolLib, LuckPerms, PlaceholderAPI, DreamCore, DreamConfig, DreamCommand]
api-version: 1.21
